export const FileConstants = {
    constants: {
        reports: 'Reports',
        observationReport: 'Observation Report',
        Loading: 'Loading...Please wait',
        hasClassList: 'hasClassList',
        CurrentProduct: 'SCOUT_CURRENT_PRODUCT',
        Tab: 'Tab',
        ArrowDown: 'ArrowDown',
        Assessment: 'Assessment',
        Grade: 'Grade',
        Kindergarten: 'Kindergarten',
        NoResultString: 'No Result Found',
        noObservationMsg: 'No Observations Found.',
        noMediaMsg: 'No Media Found.',
        noNotesMsg: 'No Notes Found.',
        selectedLink: 'Assessments',
        studentsHeaderTitle: 'Students',
        product: 'Product',
        success: 'success',
        user: 'User',
        student: 'Student',
        image: 'image',
        applicationJSON: 'application/json',
        login: 'Login',
        token: 'Token',
        scoutLocalDB: 'scoutLocalDB',
        media: 'media',
        untitled: 'untitled',
        synced: 'synced',
        notSynced: 'not synced',
        toSync: 'toSync',
        syncError: 'syncError',
        uploadError: 'upload error',
        allMedia: 'AllMedia',
        mediaid: 'mediaid',
        mediaId: 'mediaId',
        pictures: 'Pictures',
        Video: 'Video',
        video: 'video',
        dismissed: 'Dismissed',
        closedWith: 'Closed with:',
        pressEsc: 'by pressing ESC',
        clickBackdrop: 'by clicking on a backdrop',
        with: 'with:',
        allNotes: 'AllNotes',
        toDo: 'ToDo',
        notes: 'notes',
        noteTitle: 'Notes',
        mediaTitle: 'Media',
        view: 'view',
        edit: 'edit',
        studentMedia: 'StudentMedia',
        comment: 'comment',
        content: 'content',
        hidden: 'hidden',
        download: 'download',
        href: 'href',
        csvType: 'text/csv;charset=utf-8;',
        object: 'object',
        checklist: 'checklist',
        ongoing: 'ongoing',
        desc: 'desc',
        assessment: 'assessment',
        recentActivity: 'Recent Activity',
        toDoHeading: 'To-Do\'s',
        min: 'min',
        pages: 'pages/',
        dashboardTitle: 'Dashboard',
        assessmentTitle: 'Assessments',
        assessmentChecklistTitle: 'Assessment Checklists',
        attachMedia: 'Attach Media',
        editComment: 'Edit Comment',
        ongoingAssessmentTitle: 'Ongoing Assessment',
        none: 'none',
        block: 'block',
        today: 'Today',
        thisWeek: 'This week',
        search: 'Search',
        backspace: 'Backspace',
        enter: 'Enter',
        assessmentUnit: 'Unit',
        reportBenchmarks: 'benchmarks',
        reportMathPractice: 'mathpractices',
        firebaseStoragePath: 'uploads',
        reportCheckListHeading: 'Assessment Checklist Report',
        appTitle: 'scout',
        progressCircleStyle: 'dashed',
        hello: 'Hello',
        applicationPlatform: 'Pearson Realize Scout',
        record: 'Record',
        telemetry: 'telemetry',
        fetch: 'fetch',
        checklistReport: 'Assessment Checklist Report',
        observationalReport: 'Observational Assessment Report',
        observed: 'Observed',
        saveComment: 'Save Comment',
        saveMedia: 'Save Media',
        appDBName: 'PWA_DB',
        persistentDBName: 'SCOUT_PWA_PERSISTENT',
        ididx: 'id_idx',
        asessmentNavigationHeading: 'Assessment Checklists Report',
        nanoSecondsCount: 1000000000000,
        secondsCount: 1000,
        studentDetails: 'Student Details',
        telemetryVerbId: '12345',
        saveObservedStatus: 'saveObservedStatus',
        authentication: 'Authentication',
        productName: 'Scout PWA',
        experienced: 'Experienced',
        httpError: 'HTTP Error',
        check: 'Check',
        criteria: 'Criteria',
        observational: 'Observational',
        create: 'Create',
        assessmentComment: 'Comment',
        attach: 'Attach',
        checklistTitle: 'Checklist',
        checklistTypeReport: 'Assessment Checklist',
        observationalTypeReport: 'Observational Assessment',
        checklistReportView: 'Assessment Checklist Report View',
        checklistReportLoadEvent: 'Assessment Checklist Report Loading Event',
        observationReportView: 'Observational Report View',
        observationReportLoadEvent: 'Observational Report Loading Event',
        secretKey: 'secret key',
        recentLimit: 4,
        saltRoundsForPassword: 12,
        classTitle: '',
        teacherClass: 'TeacherClass',
        program: 'Program',
        currentClass: 'currentClass',
        toc: 'TOC',
        productProgram: 'ProductProgram',
        hierarchy: 'Hierarchies',
        programAssessmentMapping: 'ProgramAssessmentMapping',
        assessmentPersistantDB: 'SCOUT_PWA_PERSISTENT_ASSESSMENT',
        currentProgram: 'currentProgram',
        alphabetsString: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
        noStudentMsg: 'No student in this class.',
        class: 'Class',
        info: 'info',
        displayOrder: 'displayOrder',
        id: 'id',
        noGuardianInfoMsg: 'No Guardian Info Found. Use Edit To Add Guardian Info.',
    }
};

